### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by four43** [chrisveness/latlon-geohash#4]
This looks like a great library, curious in some Typescript typings? I can make a PR.

**Comment by chrisveness** [comment]
I've never used Typescript, so I'm not sure what's involved. My only concern is that since the library is really just a single file (plus `test.js` & `package.json`), I wouldn't want to have it overburdened by Typescript typings.

Would I be correct in thinking that all that would need to be added would be a `latlon-geohash.d.ts` file, and a `types` entry in the `package.json`? If so, I would be glad to accept a PR.

**Comment by four43** [comment]
Understandable. Bloat to support everything sucks. I ended up finding the `ngeohash` npm package which looks to have some tests and similar functionality and DefinitelyTyped has types for it. I ended up just using that library. Thanks!
